import type { CodexReference, InventoryItem, SkillTag, SkillTagDefinition, StoryBundle, StoryIconId, StorySchema } from '@/framework/schema'

const codexTermTargets: Record<string, Pick<CodexReference, 'type' | 'targetId'>> = {
  Redvale: { type: 'place', targetId: 'ash-farms' },
}

const codexTermSummaries: Record<string, string> = {
  'the lich': 'A frightened name people use for whatever is stirring the graves. It may be an old lord, a wrong burial custom, or just a rumor that makes the dead easier to explain.',
}

const storyIconAssets: Record<StoryIconId, string> = {
  lantern: '/icons/ffffff/transparent/1x1/delapouite/old-lantern.svg',
  road: '/icons/ffffff/transparent/1x1/delapouite/horizon-road.svg',
  crossroads: '/icons/ffffff/transparent/1x1/delapouite/crossroad.svg',
  codex: '/icons/ffffff/transparent/1x1/lorc/open-book.svg',
  keep: '/icons/ffffff/transparent/1x1/delapouite/castle.svg',
  forest: '/icons/ffffff/transparent/1x1/delapouite/forest.svg',
}

// Public domain / CC0 image from The Metropolitan Museum of Art Open Access:
// Fra Filippo Lippi, "Portrait of a Woman with a Man at a Casement", object 436896.
const publicDomainPortraitAsset = '/portraits/fra-filippo-lippi-portrait-public-domain.jpg'

const skillTagDefinitions: Record<SkillTag, SkillTagDefinition> = {
  'grave-lore': {
    label: 'Burial Knowledge',
    summary: 'Knows grave customs, burial signs, and how the dead are meant to rest.',
  },
  'plain-speech': {
    label: 'Plain Speaking',
    summary: 'Can cut through fear, rank, and ceremony with direct words.',
  },
  'steady-hands': {
    label: 'Steady Hands',
    summary: 'Can keep control during delicate, dangerous, or physical work.',
  },
  'raw-strength': {
    label: 'Raw Strength',
    summary: 'Can apply force, carry weight, and hold ground when a scene turns physical.',
  },
  'mental-fortitude': {
    label: 'Mental Fortitude',
    summary: 'Can remain visibly composed under dread, pressure, and exhaustion.',
  },
}

const fieldSpade: InventoryItem = {
  id: 'field-spade',
  name: 'Field Spade',
  description: 'A plain iron-edged spade with a worn haft, useful for testing ground, levering boards, and keeping distance from things that should stay buried.',
  tags: ['tool'],
  iconAssetId: 'road',
  consumable: false,
  visible: true,
}

const blessedWater: InventoryItem = {
  id: 'blessed-water',
  name: 'Blessed Water',
  description: 'A small stoppered flask blessed by a village priest. Local rumor says it can make the restless dead flinch and slow.',
  tags: ['church', 'water'],
  iconAssetId: 'lantern',
  consumable: true,
  visible: true,
}

const ironNails: InventoryItem = {
  id: 'iron-nails',
  name: 'Iron Nails',
  description: 'A palmful of coffin nails. Good iron, bent and old, useful for holding a door when hands press from the other side.',
  tags: ['iron', 'tool'],
  iconAssetId: 'keep',
  consumable: true,
  visible: true,
}

const royalWrit: InventoryItem = {
  id: 'royal-writ',
  name: 'Sealed Writ',
  description: 'King Osric’s command, stamped in red wax. It opens gates and closes excuses.',
  tags: ['proof', 'authority'],
  iconAssetId: 'codex',
  consumable: false,
  visible: true,
}

const betterKnife: InventoryItem = {
  id: 'armory-knife',
  name: 'Armory Knife',
  description: 'A narrow knife with honest balance. Not heroic, but useful when knots, straps, or hands must be cut free.',
  tags: ['iron', 'tool'],
  iconAssetId: 'lantern',
  consumable: true,
  visible: true,
}

const crackedSpearHead: InventoryItem = {
  id: 'cracked-spear-head',
  name: 'Cracked Spearhead',
  description: 'Salvaged from a weapon too poor to carry whole. It is still iron, and iron still has opinions about the dead.',
  tags: ['iron', 'salvage'],
  iconAssetId: 'keep',
  consumable: true,
  visible: true,
}

const bellClapper: InventoryItem = {
  id: 'bell-clapper',
  name: 'Silver Bell Clapper',
  description: 'The missing tongue of an old burial bell, dark with age and bright where road grit has been rubbed away.',
  tags: ['church', 'silver'],
  iconAssetId: 'codex',
  consumable: false,
  visible: true,
}

const boneCharm: InventoryItem = {
  id: 'bone-charm',
  name: 'Bone Token',
  description: 'A fingerbone wrapped in silver wire. It is ugly enough for proof, whatever tale the court chooses to tell about it.',
  tags: ['proof', 'bone'],
  iconAssetId: 'forest',
  consumable: false,
  visible: true,
}

const storySchema: StorySchema = {
  id: 'kings-lich-playable',
  title: 'The Open Graves',
  premise: 'A royal order sends an unlikely investigator through opened graves, frightened villages, and a court that would rather call sacrifice service.',
  objective: {
    summary: 'Follow the opened graves back to the thing stirring them, survive, and return with proof the court cannot bury.',
    successCondition: 'Reach Graymere Hall Return with proof from the Old Barrow and make the king acknowledge it.',
    failureCondition: 'Return without proof, abandon the investigation, or let the court bury the truth again.',
    currentHint: 'Answer the royal order, then follow the opened graves out of Graymere Hall.',
  },
  openingNarration: 'Graymere Hall smells of wet wool, old rushes, and men trying not to look afraid. A sealed writ waits on the table before King Osric, and the dead roads of Redvale open somewhere beyond the rain.',
  victoryResolution: 'The proof reaches the throne, and the dead are given names the court can no longer spend quietly.',
  defeatResolution: 'The proof falls short of the throne, and the dead keep walking beneath orders no living mouth will confess.',
  goalNodeId: 'king-return',
  designNote:
    'A contributor-authored playable story about agency-preserving narration, original scenes, varied authored choices, and lightweight consequences. The local model narrates within the schema; code owns state.',
  fixedRules: [
    'The end user plays the selected protagonist directly.',
    'The story-critical plot does not depend on which protagonist was selected; protagonist details may color narration but cannot change hard state.',
    'Authored choices decide what the protagonist can attempt; generated prose may enrich but cannot override mechanical state.',
    'Inventory is visible story state and changes only through authored effects.',
    'The protagonist’s condition is visible prose, never a number, bar, level, or percentage.',
    'The codex is compact known memory for the player and the local narrator.',
    'Unexplored places, hidden routes, and future event tables remain unrevealed until discovered.',
    'All story material and style guidance must remain original and generic, without named protected references.',
  ],
  codexTerms: ['Redvale', 'King Osric', 'Blackpine Road', 'Ash Farms', 'Old Watchtower', 'Old Barrow', 'Graymere Hall', 'Field Spade', 'Blessed Water', 'Iron Nails', 'Sealed Writ', 'the lich'],
  players: [
    {
      id: 'tamsin',
      name: 'Tamsin',
      role: 'Grave-tender under royal order',
      portraitAsset: publicDomainPortraitAsset,
      color: '#7dd3fc',
      condition: 'Tired, mud-spattered, and steady enough to keep moving.',
      inventory: [fieldSpade, blessedWater, ironNails, royalWrit],
      skillTags: ['grave-lore', 'plain-speech', 'mental-fortitude'],
      aptitudes: {
        strength: 'low',
        mentalFortitude: 'high',
      },
      voice: {
        publicStyle: 'dry, practical, and too familiar with death to flatter anyone',
        innerStyle: 'watchful, restrained, bitterly funny when fear gets close',
        fear: 'being spent by powerful people who will misname it courage',
        desire: 'to put the dead back down and return to work that makes sense',
        contradiction: 'respects burial customs but distrusts anyone who turns sacrifice into policy',
      },
      backstory: {
        origin: 'Tamsin tends graves outside Redvale and was taken by levy because she knows burial ground better than court men do.',
        wound: 'She has buried neighbors for orders written by people who never learned their names.',
        want: 'She wants to survive, end the rising dead, and make the king admit what this command costs.',
        privateKnowledge: 'Burial customs can slow panic and make frightened witnesses useful, even when they cannot explain what they saw.',
      },
      memory: ['The king called it service because he could not bear to call it fear.'],
    },
    {
      id: 'corvin-hale',
      name: 'Corvin Hale',
      role: 'Retired mercenary under royal order',
      portraitAsset: publicDomainPortraitAsset,
      color: '#f97316',
      condition: 'Broad-shouldered, travel-worn, and holding composure together by habit more than peace.',
      inventory: [fieldSpade, blessedWater, ironNails, royalWrit],
      skillTags: ['raw-strength', 'steady-hands', 'plain-speech'],
      aptitudes: {
        strength: 'high',
        mentalFortitude: 'low',
      },
      voice: {
        publicStyle: 'blunt, economical, and used to measuring exits before promises',
        innerStyle: 'tight, guarded, and easily crowded by memories of old violence',
        fear: 'freezing when the dead make battle feel personal again',
        desire: 'to finish one last paid duty without becoming the kind of weapon courts keep reaching for',
        contradiction: 'knows how to survive violence but no longer trusts what violence does to him',
      },
      backstory: {
        origin: 'Corvin Hale left mercenary work after too many winter campaigns and was pulled back by a royal writ no village could refuse.',
        wound: 'He has strength enough for doors, bodies, and road fights, but old horrors come back fastest when the dead move like soldiers.',
        want: 'He wants to get through Redvale alive, deliver proof, and return to a life where no one gives him orders at sword-point.',
        privateKnowledge: 'Frightened armed people watch posture before words; a calm stance can stop a fight before it starts.',
      },
      memory: ['The old companies taught him how to stand firm, not how to sleep afterward.'],
    },
  ],
  nodes: [
    {
      id: 'graymere-yard',
      name: 'Graymere Yard',
      publicName: 'Graymere Hall',
      canonicalDescription: 'Graymere Hall is the muddy seat of King Osric, where polished orders make the dead roads sound cleaner than they are.',
      description: 'The muddy seat of King Osric, where limewashed walls, wet rushes, and polished orders make the roads sound cleaner than they are.',
      explorationHint: 'Mud-dark roads lead away from the hall under a low sky.',
      iconAssetId: 'road',
      nodeType: 'origin',
      exits: [
        { toNodeId: 'ash-farms', direction: 'west', label: 'Follow the opened graves' },
        { toNodeId: 'old-watchtower', direction: 'east', label: 'Take the high road toward the old tower' },
      ],
      unfinishedBusiness: [
        {
          id: 'answer-royal-order',
          label: 'Answer the royal order',
          reason: 'The royal order must be answered before the road out of Graymere Hall can mean anything.',
          activeEventId: 'royal-order',
          clearedByFlag: 'royal-order-answered',
        },
      ],
      nextNodeIds: ['ash-farms', 'old-watchtower'],
      mapPosition: { x: 300, y: 520 },
      eventWeights: [
        { eventId: 'royal-order', weight: 8 },
        { eventId: 'bad-equipment', weight: 3 },
        { eventId: 'village-plea', weight: 2 },
      ],
    },
    {
      id: 'ash-farms',
      name: 'Ash Farms',
      publicName: 'Ash Farms',
      canonicalDescription: 'Ash Farms is a stretch of sickly fields outside Redvale where fresh graves keep opening and farmers count names under their breath.',
      description: 'Sickly fields outside Redvale, where fresh graves keep opening and farmers count names under their breath.',
      explorationHint: 'A rutted farm road sinks into fields and grave-cold mist.',
      iconAssetId: 'crossroads',
      nodeType: 'settlement',
      exits: [
        { toNodeId: 'graymere-yard', direction: 'east', label: 'Return to the king’s road' },
        { toNodeId: 'blackpine-road', direction: 'north', label: 'Follow the grave-road into the pines' },
        { toNodeId: 'old-watchtower', direction: 'northeast', label: 'Cut across the high fields' },
      ],
      nextNodeIds: ['graymere-yard', 'blackpine-road', 'old-watchtower'],
      mapPosition: { x: 180, y: 385 },
      eventWeights: [
        { eventId: 'burned-field', weight: 8 },
        { eventId: 'village-plea', weight: 3 },
        { eventId: 'grave-mist', weight: 2 },
      ],
    },
    {
      id: 'old-watchtower',
      name: 'Old Watchtower',
      publicName: 'Old Watchtower',
      canonicalDescription: 'The Old Watchtower is a leaning hill tower where bad maps, burial marks, and worse advice have survived the weather.',
      description: 'A leaning hill tower where bad maps, old burial customs, and worse advice have survived the weather.',
      explorationHint: 'A high path climbs toward broken stone and old warning marks.',
      iconAssetId: 'codex',
      nodeType: 'watch',
      exits: [
        { toNodeId: 'graymere-yard', direction: 'west', label: 'Descend toward Graymere Hall' },
        { toNodeId: 'ash-farms', direction: 'southwest', label: 'Cross back toward the fields' },
        { toNodeId: 'blackpine-road', direction: 'northwest', label: 'Take the marked road under the pines' },
        { toNodeId: 'barrow-crypt', direction: 'north', label: 'Follow the tower map toward the barrow' },
      ],
      nextNodeIds: ['graymere-yard', 'ash-farms', 'blackpine-road', 'barrow-crypt'],
      mapPosition: { x: 420, y: 385 },
      eventWeights: [
        { eventId: 'hermit-warning', weight: 7 },
        { eventId: 'bad-equipment', weight: 2 },
        { eventId: 'grave-mist', weight: 3 },
      ],
    },
    {
      id: 'blackpine-road',
      name: 'Blackpine Road',
      publicName: 'Blackpine Road',
      canonicalDescription: 'Blackpine Road is a cramped forest road where split carts lean under black pines and cold mist hangs low over the ruts.',
      description: 'A cramped forest road where split carts lean under black pines and cold mist hangs low over the ruts.',
      explorationHint: 'Black pines crowd a road where cold fog swallows wheel ruts.',
      iconAssetId: 'forest',
      nodeType: 'hazard',
      exits: [
        { toNodeId: 'ash-farms', direction: 'south', label: 'Return by the farm track' },
        { toNodeId: 'old-watchtower', direction: 'southeast', label: 'Climb back toward the tower' },
        { toNodeId: 'barrow-crypt', direction: 'north', label: 'Press through the mist' },
      ],
      nextNodeIds: ['ash-farms', 'old-watchtower', 'barrow-crypt'],
      mapPosition: { x: 285, y: 250 },
      eventWeights: [
        { eventId: 'grave-mist', weight: 8 },
        { eventId: 'bandit-toll', weight: 3 },
        { eventId: 'burned-field', weight: 1 },
      ],
    },
    {
      id: 'barrow-crypt',
      name: 'Old Barrow',
      publicName: 'Old Barrow',
      canonicalDescription: 'The Old Barrow is a buried hall under the hill, cold with old bones, a cracked bell, and signs that someone has been using the dead.',
      description: 'A buried hall under the hill, cold with old bones, a cracked bell, and signs that someone has been using the dead.',
      explorationHint: 'A grass-swallowed mound waits ahead with stone teeth showing.',
      iconAssetId: 'keep',
      nodeType: 'crypt',
      exits: [
        { toNodeId: 'old-watchtower', direction: 'south', label: 'Retreat by the tower path' },
        { toNodeId: 'blackpine-road', direction: 'southwest', label: 'Return through Blackpine Road' },
        {
          toNodeId: 'king-return',
          direction: 'east',
          label: 'Return to court with proof',
          blocker: {
            id: 'proof-required',
            label: 'Proof required',
            reason: 'Returning to court empty-handed would give the king another order, not proof. Something from under the hill must show what is stirring the graves.',
            requiredItemId: 'bone-charm',
          },
        },
      ],
      nextNodeIds: ['old-watchtower', 'blackpine-road', 'king-return'],
      mapPosition: { x: 300, y: 110 },
      eventWeights: [
        { eventId: 'lich-ritual', weight: 10 },
        { eventId: 'bone-charm-glimpse', weight: 3 },
      ],
    },
    {
      id: 'king-return',
      name: 'King Return',
      publicName: 'Graymere Hall Return',
      canonicalDescription: 'Graymere Hall Return is the court’s reckoning point, where survival must become proof and proof must become a sentence.',
      description: 'The return to King Osric, where survival must become proof and proof must become a sentence.',
      explorationHint: 'Torch smoke and court noise gather beyond the road back.',
      iconAssetId: 'lantern',
      nodeType: 'court',
      exits: [{ toNodeId: 'barrow-crypt', direction: 'west', label: 'Go back toward the barrow road' }],
      nextNodeIds: ['barrow-crypt'],
      mapPosition: { x: 470, y: 65 },
      eventWeights: [{ eventId: 'royal-proof', weight: 10 }],
    },
  ],
  events: [
    {
      id: 'royal-order',
      name: 'The king spends another life',
      weight: 4,
      iconAssetId: 'road',
      prompt: 'King Osric gives a stamped writ and commands one unwilling investigator to follow the opened graves back to their master.',
      currentHint: 'Get the order into plain words before choosing which road leaves the hall.',
      objectiveNodeId: 'ash-farms',
      npcTemplate: {
        id: 'king-osric',
        name: 'King Osric',
        role: 'Tired king',
        canonicalDescription: 'King Osric is a thin ruler in a patched crown who has slept badly enough to mistake command for courage.',
        description: 'A thin ruler in a patched crown who has slept badly enough to mistake command for courage.',
        voice: 'formal, clipped, ashamed when pressed, impatient with delay',
        want: 'Send someone to stop the dead before the graves around Redvale empty out.',
        knows: 'The old barrow beyond Blackpine Road is where the trouble seems to start, and the last knight returned pale, silent, and dead-eyed before vanishing at dawn.',
      },
      choices: [
        {
          id: 'make-king-name-cost',
          label: 'Make the king name what he is asking of you',
          neutralSummary: 'You pressed for plain accountability instead of accepting the order silently.',
          writerIntent: 'Offer a direct social option that challenges power without choosing exact words for the player.',
          actionPrompt: 'The selected option is to press King Osric to speak plainly about sending one more subject where trained knights failed.',
          mode: 'ask',
          displayStyle: 'dialogue',
          skillTags: ['plain-speech'],
          effects: [
            { type: 'setFlag', flag: 'royal-order-answered', value: true },
            { type: 'remember', text: 'King Osric admitted the old barrow beyond Blackpine Road may be where the dead are being stirred.' },
            { type: 'revealNode', nodeId: 'ash-farms' },
            { type: 'moveToNode', nodeId: 'ash-farms' },
          ],
        },
        {
          id: 'inspect-writ',
          label: 'Study the Sealed Writ for what it can open',
          neutralSummary: 'You looked for the practical authority the writ granted before leaving the hall.',
          writerIntent: 'Offer an investigative alternative that treats royal authority as a tool, not a feeling.',
          actionPrompt: 'The selected option is to study the Sealed Writ for practical access, demands, and obligations it can create.',
          mode: 'act',
          displayStyle: 'action',
          skillTags: ['grave-lore'],
          effects: [
            { type: 'setFlag', flag: 'royal-order-answered', value: true },
            { type: 'remember', text: 'The Sealed Writ can demand shelter, testimony, and access to closed roads.' },
            { type: 'revealNode', nodeId: 'old-watchtower' },
            { type: 'moveToNode', nodeId: 'old-watchtower' },
          ],
        },
      ],
    },
    {
      id: 'bad-equipment',
      name: 'The armory offers insult as steel',
      weight: 5,
      iconAssetId: 'lantern',
      prompt: 'The armory clerk offers a spear with a split shaft and waits for the insult to be accepted quietly.',
      currentHint: 'Secure something useful before the road makes the court’s insult dangerous.',
      objectiveNodeId: 'old-watchtower',
      choices: [
        {
          id: 'demand-usable-iron',
          label: 'Demand usable iron before leaving',
          neutralSummary: 'You turned the bad equipment into a public problem the clerk had to answer.',
          writerIntent: 'Give the player a forceful speech-intent option that improves preparation.',
          actionPrompt: 'The selected option is to press the armory clerk for gear that will not fail at the first dead hand.',
          mode: 'say',
          displayStyle: 'dialogue',
          skillTags: ['plain-speech'],
          effects: [
            { type: 'gainItem', item: betterKnife },
            { type: 'remember', text: 'The armory had to admit the first weapon was meant for someone disposable.' },
            { type: 'moveToNode', nodeId: 'old-watchtower' },
          ],
        },
        {
          id: 'salvage-spear-head',
          label: 'Salvage the spearhead and leave the shaft behind',
          neutralSummary: 'You took the only useful part and avoided giving the clerk another opening to posture.',
          writerIntent: 'Offer a quiet practical option that converts bad gear into a useful item.',
          actionPrompt: 'The selected option is to strip useful iron from the broken spear and leave the useless shaft behind.',
          mode: 'act',
          displayStyle: 'action',
          skillTags: ['steady-hands'],
          effects: [
            { type: 'gainItem', item: crackedSpearHead },
            { type: 'moveToNode', nodeId: 'old-watchtower' },
          ],
        },
      ],
    },
    {
      id: 'village-plea',
      name: 'A farmer asks which kind of mercy this is',
      weight: 3,
      iconAssetId: 'crossroads',
      prompt: 'A farmer blocks the road with a child behind him and asks whether the royal writ has come to bury the village or save it.',
      currentHint: 'Listen for what the farms know about the first opened grave.',
      objectiveNodeId: 'ash-farms',
      npcTemplate: {
        id: 'farmer-riel',
        name: 'Farmer Riel',
        role: 'Frightened father',
        canonicalDescription: 'Farmer Riel is a raw-eyed farmer with mud on his knees and a child gripping the back of his coat.',
        description: 'A raw-eyed farmer with mud on his knees and a child gripping the back of his coat.',
        voice: 'plain, guarded, angry from fear',
        want: 'Know whether the royal order brings help or another lie.',
        knows: 'Three graves opened behind his byre after a bell rang under the hill.',
      },
      choices: [
        {
          id: 'answer-with-truth',
          label: 'Answer him with the truth you can afford',
          neutralSummary: 'You gave a limited honest answer and left room for what was still unknown.',
          writerIntent: 'Offer an empathetic conversational option without writing exact player dialogue.',
          actionPrompt: 'The selected option is to answer Farmer Riel honestly about what is known, what is unknown, and the next intended step.',
          mode: 'say',
          displayStyle: 'dialogue',
          skillTags: ['plain-speech'],
          effects: [
            { type: 'remember', text: 'A bell rang beneath the hill before the Ash Farms graves opened.' },
            { type: 'moveToNode', nodeId: 'ash-farms' },
          ],
        },
        {
          id: 'show-writ',
          label: 'Show the Sealed Writ and ask for the first opened grave',
          neutralSummary: 'You used official authority to focus the exchange on a concrete lead.',
          writerIntent: 'Offer an authority-backed investigative option that may create distrust but gains direction.',
          actionPrompt: 'The selected option is to show the Sealed Writ as authority to demand a path to the first disturbed grave.',
          mode: 'ask',
          displayStyle: 'dialogue',
          skillTags: ['grave-lore'],
          requiresItem: 'royal-writ',
          effects: [
            { type: 'remember', text: 'The first opened grave at Ash Farms belonged to a bell-ringer buried without his clapper.' },
            { type: 'moveToNode', nodeId: 'ash-farms' },
          ],
        },
      ],
    },
    {
      id: 'burned-field',
      name: 'The field has too many open mouths',
      weight: 2,
      iconAssetId: 'forest',
      prompt: 'Old graves gape open around a farm while someone pounds from beneath a root cellar door.',
      currentHint: 'Control the danger long enough to learn what came from the east.',
      objectiveNodeId: 'blackpine-road',
      npcTemplate: {
        id: 'miller-joan',
        name: 'Miller Joan',
        role: 'Injured farmer',
        canonicalDescription: 'Miller Joan is a mud-covered miller with a shaking lantern and no patience for ceremonial courage.',
        description: 'A mud-covered miller with a shaking lantern and no patience for ceremonial courage.',
        voice: 'plain, angry, frightened, and practical',
        want: 'Get her brother out of the root cellar before the dead find the door.',
        knows: 'The dead came from the east after the bell rang under the hill, and one corpse still wore a royal tabard.',
      },
      choices: [
        {
          id: 'seal-cellar-with-nails',
          label: 'Use Iron Nails to hold the cellar shut',
          neutralSummary: 'You spent the nails to buy time and control the rescue.',
          writerIntent: 'Offer a careful item-use option that trades inventory for safety.',
          actionPrompt: 'The selected option is to brace the cellar door with coffin nails and coordinate when the people below should move.',
          mode: 'use-item',
          displayStyle: 'action',
          skillTags: ['steady-hands'],
          requiresItem: 'iron-nails',
          effects: [
            { type: 'loseItem', itemId: 'iron-nails' },
            { type: 'remember', text: 'Miller Joan saw a corpse in royal colors among the dead from the east.' },
            { type: 'moveToNode', nodeId: 'blackpine-road' },
          ],
        },
        {
          id: 'throw-blessed-water',
          label: 'Throw Blessed Water into the nearest dead face',
          neutralSummary: 'You spent the Blessed Water for a fast opening, accepting that close work might hurt.',
          writerIntent: 'Offer a risky item-use option with a clear cost.',
          actionPrompt: 'The selected option is to spend Blessed Water to slow the nearest corpse long enough to open the root cellar.',
          mode: 'use-item',
          displayStyle: 'action',
          skillTags: ['grave-lore'],
          requiresItem: 'blessed-water',
          effects: [
            { type: 'loseItem', itemId: 'blessed-water' },
            { type: 'remember', text: 'The dead clawed close while the cellar opened.' },
            { type: 'remember', text: 'Blessed Water can slow the dead, but only for moments.' },
            { type: 'moveToNode', nodeId: 'blackpine-road' },
          ],
        },
      ],
    },
    {
      id: 'hermit-warning',
      name: 'The tower keeps an ugly warning',
      weight: 5,
      iconAssetId: 'codex',
      prompt: 'A hermit at the old watchtower says the dead began walking after someone stole from a burial bell under the hill.',
      currentHint: 'Turn the hermit’s ugly warning into a practical way into the barrow.',
      objectiveNodeId: 'barrow-crypt',
      npcTemplate: {
        id: 'old-perrin',
        name: 'Old Perrin',
        role: 'Tower hermit',
        canonicalDescription: 'Old Perrin is a sharp-eyed hermit who has survived by being useful and unpleasant in equal measure.',
        description: 'A sharp-eyed hermit who has survived by being useful and unpleasant in equal measure.',
        voice: 'rasping, blunt, fond of ugly truths',
        want: 'Convince the royal appointee that courage without care will only add a fresh body to the road.',
        knows: 'A fingerbone token lies near a silver burial bell under the hill, and the bell lacks its clapper.',
      },
      choices: [
        {
          id: 'trade-for-rite',
          label: 'Trade plain answers for the burial custom',
          neutralSummary: 'You treated the hermit as a bargainer and exchanged facts for useful instructions.',
          writerIntent: 'Offer a direct social option that rewards candor with practical burial knowledge.',
          actionPrompt: 'The selected option is to give Old Perrin plain answers about the opened graves and demand the burial instructions in return.',
          mode: 'say',
          displayStyle: 'dialogue',
          skillTags: ['plain-speech'],
          effects: [
            { type: 'gainItem', item: bellClapper },
            { type: 'remember', text: 'The burial bell may matter because the dead began walking after its clapper went missing.' },
            { type: 'moveToNode', nodeId: 'barrow-crypt' },
          ],
        },
        {
          id: 'read-the-tower-marks',
          label: 'Read the burial marks carved into the tower stair',
          neutralSummary: 'You relied on physical evidence instead of the hermit’s performance.',
          writerIntent: 'Offer an investigative option that uses the protagonist’s grave knowledge.',
          actionPrompt: 'The selected option is to study the old burial marks carved into the tower stairwell for usable instructions.',
          mode: 'act',
          displayStyle: 'action',
          skillTags: ['grave-lore'],
          effects: [
            { type: 'remember', text: 'The barrow marks link the bell, a fingerbone token, and the old names of the buried dead.' },
            { type: 'revealNode', nodeId: 'barrow-crypt' },
            { type: 'moveToNode', nodeId: 'barrow-crypt' },
          ],
        },
      ],
    },
    {
      id: 'grave-mist',
      name: 'The mist learns to listen',
      weight: 6,
      iconAssetId: 'forest',
      prompt: 'Cold mist and broken pines show the dead are close enough to hear careless breath.',
      currentHint: 'Keep moving toward the barrow without letting the mist decide the route.',
      objectiveNodeId: 'barrow-crypt',
      choices: [
        {
          id: 'mark-safe-path',
          label: 'Mark a quiet path with the Field Spade',
          neutralSummary: 'You used the Field Spade as a practical tool to test ground and choose a safer route.',
          writerIntent: 'Offer a careful tool-use option that avoids stating obvious item affordances as tags.',
          actionPrompt: 'The selected option is to use the Field Spade to test soft earth and mark a path where the mist lies thinnest.',
          mode: 'use-item',
          displayStyle: 'action',
          skillTags: ['grave-lore', 'steady-hands'],
          requiresItem: 'field-spade',
          effects: [
            { type: 'remember', text: 'The mist thickens around disturbed royal dead.' },
            { type: 'moveToNode', nodeId: 'barrow-crypt' },
          ],
        },
        {
          id: 'run-through-mist',
          label: 'Run before the mist closes',
          neutralSummary: 'You traded safety for speed before the dead fully gathered.',
          writerIntent: 'Offer a high-risk option where speed leaves visible strain and danger in the narration.',
          actionPrompt: 'The selected option is to choose speed over silence and break through the mist before the dead fully gather.',
          mode: 'risk',
          displayStyle: 'action',
          skillTags: ['steady-hands'],
          effects: [
            { type: 'remember', text: 'The cold mist burned where it touched living skin.' },
            { type: 'moveToNode', nodeId: 'barrow-crypt' },
          ],
        },
      ],
    },
    {
      id: 'bandit-toll',
      name: 'Deserters ask the dead country for rent',
      weight: 2,
      iconAssetId: 'crossroads',
      prompt: 'Hungry deserters demand food, tools, and the writ before allowing anyone into the dead country.',
      currentHint: 'Get past the deserters with enough strength and proof-seeking tools intact.',
      objectiveNodeId: 'barrow-crypt',
      npcTemplate: {
        id: 'sergeant-maud',
        name: 'Sergeant Maud',
        role: 'Deserter with a borrowed sword',
        canonicalDescription: 'Sergeant Maud is a hollow-cheeked veteran whose shame has hardened into toll-taking.',
        description: 'A hollow-cheeked veteran whose shame has hardened into toll-taking.',
        voice: 'dry, threatening, tired beneath the threat',
        want: 'Take enough from travelers to keep her deserters alive another week.',
        knows: 'The royal dead walk first when the bell sounds, as if old commands still pull them upright.',
      },
      choices: [
        {
          id: 'show-royal-dead-truth',
          label: 'Tell the deserters what walks in royal colors',
          neutralSummary: 'You used the deserters’ own fear and experience to make the roadblock feel pointless.',
          writerIntent: 'Offer a direct conversational option that uses known evidence without exact dialogue.',
          actionPrompt: 'The selected option is to tell Sergeant Maud about the royal corpse and challenge whether blocking this investigation helps anyone survive.',
          mode: 'say',
          displayStyle: 'dialogue',
          skillTags: ['plain-speech'],
          effects: [
            { type: 'remember', text: 'The royal dead may be walking first because old commands still cling to them.' },
            { type: 'moveToNode', nodeId: 'barrow-crypt' },
          ],
        },
        {
          id: 'trade-knife-for-passage',
          label: 'Trade the Armory Knife for quiet passage',
          neutralSummary: 'You gave up a useful object to avoid violence and keep moving.',
          writerIntent: 'Offer a careful inventory trade that avoids a fight.',
          actionPrompt: 'The selected option is to trade the Armory Knife for passage without a fight.',
          mode: 'use-item',
          displayStyle: 'action',
          skillTags: ['plain-speech'],
          requiresItem: 'armory-knife',
          effects: [
            { type: 'loseItem', itemId: 'armory-knife' },
            { type: 'remember', text: 'Avoiding the fight preserved strength for the road ahead.' },
            { type: 'moveToNode', nodeId: 'barrow-crypt' },
          ],
        },
      ],
    },
    {
      id: 'bone-charm-glimpse',
      name: 'The bone token shows itself',
      weight: 4,
      iconAssetId: 'keep',
      prompt: 'A dead man in rotted finery turns toward the bell, revealing a fingerbone token threaded with silver wire beneath its robes.',
      currentHint: 'Take proof from the barrow without giving the dead another body to carry.',
      objectiveNodeId: 'king-return',
      choices: [
        {
          id: 'hook-charm-with-spade',
          label: 'Hook the Bone Token with the Field Spade',
          neutralSummary: 'You used reach and leverage to take the charm without barehanded contact.',
          writerIntent: 'Offer a risky tool-use option where the cost is handled through visible narrative consequence.',
          actionPrompt: 'The selected option is to use the Field Spade to hook the Bone Token away from the dead man without touching it barehanded.',
          mode: 'use-item',
          displayStyle: 'action',
          skillTags: ['steady-hands'],
          requiresItem: 'field-spade',
          effects: [
            { type: 'gainItem', item: boneCharm },
            { type: 'remember', text: 'The corpse’s cold bit through the spade haft.' },
            { type: 'remember', text: 'The Bone Token may be the proof that someone has been using the dead.' },
            { type: 'moveToNode', nodeId: 'king-return' },
          ],
        },
        {
          id: 'speak-burial-name',
          label: 'Speak the burial name and reach for the token',
          neutralSummary: 'You used the burial name to make the dead pause, then took the opening it created.',
          writerIntent: 'Offer a reflective burial-knowledge option without inventing exact spoken words.',
          actionPrompt: 'The selected option is to invoke the burial name and reach for the token while the dead man hesitates.',
          mode: 'say',
          displayStyle: 'dialogue',
          skillTags: ['grave-lore'],
          effects: [
            { type: 'gainItem', item: boneCharm },
            { type: 'remember', text: 'Naming the dead can slow them when the old burial customs still hold.' },
            { type: 'moveToNode', nodeId: 'king-return' },
          ],
        },
      ],
    },
    {
      id: 'lich-ritual',
      name: 'The dead rise to the wrong bell',
      weight: 10,
      iconAssetId: 'keep',
      prompt: 'The dead begin rising again in the Old Barrow while a cracked burial bell swings without its missing voice.',
      currentHint: 'Break the command over the dead, or escape with proof before the barrow closes.',
      objectiveNodeId: 'king-return',
      choices: [
        {
          id: 'restore-bell-and-break-charm',
          label: 'Restore the bell and break the Bone Token',
          neutralSummary: 'You made the burial bell whole and used it to turn the dead away.',
          writerIntent: 'Offer the strongest prepared burial-custom solution for players who found the clapper.',
          actionPrompt: 'The selected option is to set the Silver Bell Clapper into the burial bell, ring it, and break the Bone Token as the dead turn toward the sound.',
          mode: 'use-item',
          displayStyle: 'action',
          skillTags: ['grave-lore', 'steady-hands'],
          requiresItem: 'bell-clapper',
          effects: [
            { type: 'gainItem', item: boneCharm },
            { type: 'remember', text: 'The burial bell rang whole, and the dead lost whatever command held them upright.' },
            { type: 'setFlag', flag: 'lich-ended', value: true },
            { type: 'moveToNode', nodeId: 'king-return' },
          ],
        },
        {
          id: 'bind-crypt-with-iron',
          label: 'Bar the barrow door with scavenged iron',
          neutralSummary: 'You used scavenged iron to hold the door when a clean ending was not available.',
          writerIntent: 'Offer a costly fallback that can still carry the story forward.',
          actionPrompt: 'The selected option is to use every available scrap of iron to bar the barrow door long enough to escape with proof.',
          mode: 'use-item',
          displayStyle: 'action',
          skillTags: ['steady-hands'],
          requiresItem: 'cracked-spear-head',
          effects: [
            { type: 'loseItem', itemId: 'cracked-spear-head' },
            { type: 'remember', text: 'The barrow fought back with dead hands and falling stone.' },
            { type: 'gainItem', item: boneCharm },
            { type: 'setFlag', flag: 'lich-contained', value: true },
            { type: 'moveToNode', nodeId: 'king-return' },
          ],
        },
        {
          id: 'grab-proof-and-run',
          label: 'Grab the Bone Token and run for the road',
          neutralSummary: 'You took the ugly proof and fled before the barrow could close around you.',
          writerIntent: 'Provide an always-available escape route so the player can never be trapped at the climax without a required item.',
          actionPrompt: 'The selected option is to seize the Bone Token in the confusion and escape the barrow with proof. Make the escape costly and frightening, but do not block progress.',
          mode: 'risk',
          displayStyle: 'action',
          skillTags: ['raw-strength', 'steady-hands'],
          effects: [
            { type: 'remember', text: 'The barrow nearly closed around the escape, but the Bone Token came out into living air.' },
            { type: 'gainItem', item: boneCharm },
            { type: 'setFlag', flag: 'lich-escaped-with-proof', value: true },
            { type: 'moveToNode', nodeId: 'king-return' },
          ],
        },
      ],
    },
    {
      id: 'royal-proof',
      name: 'Proof dirties the throne room',
      weight: 10,
      iconAssetId: 'lantern',
      prompt: 'The investigation returns to King Osric with mud, wounds, and whatever proof could be carried from under the hill.',
      currentHint: 'Make the proof public enough that the court cannot rename it service.',
      choices: [
        {
          id: 'lay-proof-before-king',
          label: 'Lay the proof before the king and make him look',
          neutralSummary: 'You used the carried evidence to force public acknowledgment.',
          writerIntent: 'Offer a direct ending option focused on accountability and proof.',
          actionPrompt: 'The selected option is to lay the proof before King Osric and force public acknowledgment of the order’s cost.',
          mode: 'act',
          displayStyle: 'action',
          skillTags: ['plain-speech'],
          requiresItem: 'bone-charm',
          effects: [
            { type: 'remember', text: 'Proof returned to court and made the king look at what his command cost.' },
            { type: 'setFlag', flag: 'proof-delivered', value: true },
          ],
        },
        {
          id: 'demand-names-read',
          label: 'Demand the names of the dead be read before reward',
          neutralSummary: 'You made witness and remembrance the price of any royal gratitude.',
          writerIntent: 'Offer a reflective ending option that centers the dead rather than reward.',
          actionPrompt: 'The selected option is to refuse reward until the names of the raised and reburied dead are read aloud in the hall.',
          mode: 'say',
          displayStyle: 'dialogue',
          skillTags: ['grave-lore', 'plain-speech'],
          effects: [
            { type: 'remember', text: 'The dead were given witness before any royal gratitude could make the matter clean.' },
            { type: 'setFlag', flag: 'proof-delivered', value: true },
          ],
        },
      ],
    },
  ],
}

export const openGravesStory = {
  schema: storySchema,
  iconAssets: storyIconAssets,
  skillTagDefinitions,
  allKnownItems: [fieldSpade, blessedWater, ironNails, royalWrit, betterKnife, crackedSpearHead, bellClapper, boneCharm],
  codexTermTargets,
  codexTermSummaries,
  runtime: {
    initialNodeId: 'graymere-yard',
    initialExploredNodeIds: ['graymere-yard'],
    victory: {
      goalNodeId: storySchema.goalNodeId,
      requiredFlag: 'proof-delivered',
    },
    currentObjectiveText: {
      won: 'The proof has been delivered; the hall now has to hear the dead by name.',
      lost: 'The road can go no farther; the dead keep walking under orders no one will admit giving.',
    },
    outcomeFeedText: {
      won: 'The proof has been delivered. The dead have names again, and the hall has to hear them.',
      lost: 'The road can go no farther. Somewhere ahead, the dead keep walking under orders no living mouth will admit giving.',
    },
    narrationStyleRule: 'For texture, favor grounded medieval hardship, plain names, practical social friction, and simple burial customs; do not copy or evoke any specific external work.',
  },
} satisfies StoryBundle
