import type { CodexReference, InventoryItem, SkillTag, SkillTagDefinition, StoryBundle, StoryIconId, StorySchema } from '@/framework/schema'
import type { StoryBible } from '@/framework/story-bible'

const codexTermTargets: Record<string, Pick<CodexReference, 'type' | 'targetId'>> = {
  Redvale: { type: 'place', targetId: 'ash-farms' },
  'Tamsin Vale': { type: 'person', targetId: 'tamsin' },
  'Corvin Hale': { type: 'person', targetId: 'corvin-hale' },
  'King Osric': { type: 'person', targetId: 'king-osric' },
  'Father Aldric': { type: 'person', targetId: 'father-aldric' },
  Maren: { type: 'person', targetId: 'maren' },
  'Royal Archivist Renwick': { type: 'person', targetId: 'royal-archivist-renwick' },
  'Graymere Court': { type: 'term', targetId: 'graymere-court' },
  'Redvale Church': { type: 'term', targetId: 'redvale-church' },
  'Redvale Villagers': { type: 'term', targetId: 'redvale-villagers' },
  'Royal Archivists': { type: 'term', targetId: 'royal-archivists' },
  'Famine Records': { type: 'item', targetId: 'grave-ledger' },
  'Opened Graves': { type: 'term', targetId: 'opened-graves' },
  'Contested Evidence': { type: 'item', targetId: 'contested-evidence' },
}

const codexTermSummaries: Record<string, string> = {
  redvale: 'A famine-marked village whose opened graves have become a struggle over memory, records, fear, and public truth.',
  'tamsin vale': 'A Redvale grave-tender whose younger brother was recorded under the wrong famine body; she knows how official truth can bury a living witness.',
  'corvin hale': 'A retired mercenary who once helped execute an innocent noble on weak evidence and now distrusts every clean conclusion.',
  'king osric': 'A tired king who fears panic could break the realm and believes a public answer may hold it together.',
  'father aldric': 'Redvale’s priest, famous for rewriting every sermon because he believes certainty is the root of cruelty.',
  maren: 'A burial rememberer who can recite every grave, name, family, and year, but cannot reliably remember living faces.',
  'royal archivist renwick': 'The keeper of royal records, sincere in his terror that if records can be wrong, kingdoms cannot exist.',
  'graymere court': 'The royal faction that needs order restored before panic becomes rebellion, and may mistake a sealed answer for trust.',
  'redvale church': 'The spiritual authority over Redvale’s grief, correct that rites and wounds matter, dangerous when metaphor replaces accountability.',
  'redvale villagers': 'Families and famine survivors who know something strange is happening and fear the kingdom will forget them again.',
  'royal archivists': 'Record keepers who preserve law across time, and may preserve falsehood rather than admit the archive can wound.',
  'famine records': 'Burial rolls, relief lists, and copied entries from the famine years; some are too tidy to be trusted and too important to discard.',
  'opened graves': 'The violated graves around Redvale. They may indicate crime, panic, fraud, sabotage, spiritual fracture, or something still unnamed.',
  'contested evidence': 'A bundle of soil, copied entries, witness marks, and disputed objects that can support several explanations without settling them.',
}

const storyIconAssets: Record<StoryIconId, string> = {
  lantern: '/icons/old-lantern.svg',
  road: '/icons/horizon-road.svg',
  crossroads: '/icons/crossroad.svg',
  codex: '/icons/open-book.svg',
  keep: '/icons/delapouite-castle.svg',
  forest: '/icons/forest.svg',
  fieldSpade: '/icons/trench-spade.svg',
  blessedWater: '/icons/holy-water.svg',
  ironNails: '/icons/nails.svg',
  royalWrit: '/icons/scroll-quill.svg',
  armoryKnife: '/icons/plain-dagger.svg',
  crackedSpearHead: '/icons/barbed-spear.svg',
  bellClapper: '/icons/ringing-bell.svg',
  boneCharm: '/icons/charm.svg',
}

// Public domain / CC0 image from The Metropolitan Museum of Art Open Access:
// Fra Filippo Lippi, "Portrait of a Woman with a Man at a Casement", object 436896.
const publicDomainPortraitAsset = '/portraits/fra-filippo-lippi-portrait-public-domain.jpg'

const skillTagDefinitions: Record<SkillTag, SkillTagDefinition> = {
  'grave-lore': {
    label: 'Burial Knowledge',
    summary: 'Knows grave customs, burial signs, family memory, and how records can fail the dead.',
  },
  'plain-speech': {
    label: 'Plain Speaking',
    summary: 'Can cut through fear, rank, ceremony, and defensive certainty with direct words.',
  },
  'steady-hands': {
    label: 'Steady Hands',
    summary: 'Can keep control during delicate, dangerous, or evidentiary work.',
  },
  'raw-strength': {
    label: 'Raw Strength',
    summary: 'Can apply force, carry weight, and hold ground when a scene turns physical.',
  },
  'mental-fortitude': {
    label: 'Mental Fortitude',
    summary: 'Can remain visibly composed under dread, pressure, accusation, and institutional force.',
  },
}

const fieldSpade: InventoryItem = {
  id: 'field-spade',
  name: 'Field Spade',
  description: 'A plain iron-edged spade with a worn haft, useful for testing ground, lifting soil cleanly, and showing when a grave was opened by tool rather than weather.',
  tags: ['tool', 'burial'],
  iconAssetId: 'fieldSpade',
  consumable: false,
  visible: true,
}

const blessedWater: InventoryItem = {
  id: 'blessed-water',
  name: 'Blessed Water',
  description: 'A stoppered flask from Redvale’s church. It comforts some witnesses, offends others, and proves only that grief wants ritual language.',
  tags: ['church', 'ritual'],
  iconAssetId: 'blessedWater',
  consumable: true,
  visible: true,
}

const ironNails: InventoryItem = {
  id: 'iron-nails',
  name: 'Iron Nails',
  description: 'A palmful of coffin nails. Good iron, bent and old, useful for pinning boards, marking places, and making a temporary seal visible to witnesses.',
  tags: ['iron', 'tool'],
  iconAssetId: 'ironNails',
  consumable: true,
  visible: true,
}

const royalWrit: InventoryItem = {
  id: 'royal-writ',
  name: 'Sealed Writ',
  description: 'King Osric’s command, stamped in red wax. It opens gates, summons testimony, and makes every answer feel like it may become law.',
  tags: ['authority', 'records'],
  iconAssetId: 'royalWrit',
  consumable: false,
  visible: true,
}

const graveLedger: InventoryItem = {
  id: 'grave-ledger',
  name: 'Grave Ledger',
  description: 'A parish ledger wrapped in oilcloth, crowded with names that look settled until living memory starts reading over your shoulder.',
  tags: ['records', 'names'],
  iconAssetId: 'codex',
  consumable: false,
  visible: true,
}

const mirehillWhistle: InventoryItem = {
  id: 'mirehill-whistle',
  name: 'Mirehill Whistle',
  description: 'A dented campaign whistle Corvin will not blow. It reminds him that lawful orders can still make a man guilty.',
  tags: ['memory', 'command'],
  iconAssetId: 'bellClapper',
  consumable: false,
  visible: true,
}

const betterKnife: InventoryItem = {
  id: 'armory-knife',
  name: 'Armory Knife',
  description: 'A narrow knife with honest balance. Not heroic, but useful when ropes, seals, bindings, or prewritten conclusions must be cut open.',
  tags: ['iron', 'tool'],
  iconAssetId: 'armoryKnife',
  consumable: true,
  visible: true,
}

const crackedSpearHead: InventoryItem = {
  id: 'cracked-spear-head',
  name: 'Cracked Spearhead',
  description: 'Salvaged from a weapon too poor to carry whole. It is still useful as a wedge, marker, scraper, or warning left in plain sight.',
  tags: ['iron', 'salvage'],
  iconAssetId: 'crackedSpearHead',
  consumable: true,
  visible: true,
}

const bellClapper: InventoryItem = {
  id: 'bell-clapper',
  name: 'Silver Bell Clapper',
  description: 'The missing tongue of an old burial bell, dark with age. It may be theft, relic, ritual absence, staged sign, or coincidence given shape.',
  tags: ['church', 'evidence'],
  iconAssetId: 'bellClapper',
  consumable: false,
  visible: true,
}

const contestedEvidence: InventoryItem = {
  id: 'contested-evidence',
  name: 'Contested Evidence',
  description: 'A wrapped bundle of copied burial entries, grave soil, witness marks, missing tokens, and disputed objects whose meaning changes depending on who is allowed to explain it.',
  tags: ['proof', 'records', 'burial'],
  iconAssetId: 'boneCharm',
  consumable: false,
  visible: true,
}

const WRITER_GUIDELINES = [
  'Mysteries are about people, not answers.',
  'Every clue should reveal character.',
  'Every faction is partially correct.',
  'Every faction is partially wrong.',
  'Nobody believes they are the villain.',
  'Certainty is suspicious.',
  'The player investigates interpretations, not facts.',
  'The story should leave room for disagreement.',
  'Never confirm liches, necromancy, undead, divine punishment, or one definitive cause.',
  'Every major explanation must protect something its believers cannot bear to lose.',
]

const storySchema: StorySchema = {
  id: 'open-graves-playable',
  title: 'The Open Graves',
  premise: 'Opened graves in Redvale force a royal investigation where Court, Church, villagers, and archivists each need a different truth to survive.',
  objective: {
    summary: 'Investigate Redvale’s opened graves, gather evidence every faction can twist, and decide which version of the truth survives at court.',
    successCondition: 'Reach Graymere Hall Return with contested evidence strong enough to make King Osric’s court hear more than one explanation.',
    failureCondition: 'Let one convenient certainty become law before the graves, famine records, and living witnesses can contradict it.',
    currentHint: 'Answer the royal order, then gather competing interpretations from Redvale before court, church, villagers, and archivists close around their preferred truths.',
  },
  openingNarration:
    'The first grave opened in spring. Nobody talked about it. The second opened a week later. People talked about little else. By the fifth grave, Redvale had developed the kind of silence only villages possess: the silence of people who have begun watching one another. Three children swear they saw a dead man walking the river road. Two widows swear they buried him. Father Aldric has rewritten Sunday’s sermon four times. No version has satisfied him. At dusk, a messenger arrives from Graymere Hall. He carries questions. Everyone already has answers.',
  victoryResolution: 'The court record now contains contradiction, correction, and doubt. Redvale has not been solved, but no one owns the graves alone.',
  defeatResolution: 'A clean answer hardens around Redvale. It is simple enough to punish with and too narrow to heal anything.',
  goalNodeId: 'king-return',
  designNote:
    'A contributor-authored playable story about contested truth, agency-preserving narration, original scenes, varied authored choices, and lightweight consequences. The local model narrates within the schema; code owns state.',
  fixedRules: [
    'The end user plays the selected protagonist directly.',
    'The story-critical plot does not depend on which protagonist was selected; protagonist details may color narration but cannot change hard state.',
    'Authored choices decide what the protagonist can attempt; generated prose may enrich but cannot override tracked story facts.',
    'Inventory is visible story state and changes only through authored effects.',
    'The protagonist’s condition is visible prose, never a number, bar, level, or percentage.',
    'The codex is compact known memory for the player and the local narrator.',
    'Unexplored places, hidden routes, and future event tables remain unrevealed until discovered.',
    'All story material and style guidance must remain original and generic, without named protected references.',
    'No scene may prove a single supernatural, criminal, political, clerical, archival, or psychological cause for the opened graves.',
  ],
  codexTerms: [
    'Redvale',
    'Tamsin Vale',
    'Corvin Hale',
    'King Osric',
    'Father Aldric',
    'Maren',
    'Royal Archivist Renwick',
    'Graymere Court',
    'Redvale Church',
    'Redvale Villagers',
    'Royal Archivists',
    'Blackpine Road',
    'Ash Farms',
    'Old Watchtower',
    'Old Barrow',
    'Graymere Hall',
    'Famine Records',
    'Opened Graves',
    'Contested Evidence',
  ],
  players: [
    {
      id: 'tamsin',
      firstName: 'Tamsin',
      lastName: 'Vale',
      role: 'Redvale grave-tender under royal order',
      portraitAsset: publicDomainPortraitAsset,
      color: '#7dd3fc',
      condition: 'Tired, mud-spattered, and steady enough to read a grave before trusting a record.',
      inventory: [fieldSpade, blessedWater, graveLedger, royalWrit],
      skillTags: ['grave-lore', 'plain-speech', 'mental-fortitude'],
      aptitudes: {
        strength: 'low',
        mentalFortitude: 'high',
      },
      voice: {
        publicStyle: 'dry, practical, and too familiar with death to flatter anyone',
        innerStyle: 'watchful, restrained, and sharpest when a clean record starts sounding like a grave lid',
        fear: 'watching another wrong body become official because everyone needs the record to be correct',
        desire: 'to make the court admit that a written name can still bury a lie',
        contradiction: 'keeps burial records because names matter, but knows records can become weapons against memory',
      },
      backstory: {
        origin: 'Tamsin Vale keeps Redvale’s parish graves and was taken by royal order because she can read burial ground better than court men can read reports.',
        wound: 'During the famine, her younger brother died; the body delivered under his name was not him, and nobody believed her because the burial record needed to remain correct.',
        want: 'She wants the opened graves investigated without letting another clean record erase a wrong body.',
        privateKnowledge: 'A correct-looking burial record can be another kind of grave if everyone needs it to be true.',
      },
      memory: ['In the famine year, Tamsin was given a body under her brother’s name and knew by the hands it was not him; the record said otherwise, and the record won.'],
    },
    {
      id: 'corvin-hale',
      firstName: 'Corvin',
      lastName: 'Hale',
      role: 'Retired mercenary under royal order',
      portraitAsset: publicDomainPortraitAsset,
      color: '#f97316',
      condition: 'Broad-shouldered, travel-worn, and slower to judge than his old commanders would have tolerated.',
      inventory: [ironNails, betterKnife, mirehillWhistle, royalWrit],
      skillTags: ['raw-strength', 'steady-hands', 'plain-speech'],
      aptitudes: {
        strength: 'high',
        mentalFortitude: 'low',
      },
      voice: {
        publicStyle: 'blunt, economical, and careful to separate what is known from what is wanted',
        innerStyle: 'tight, guarded, and crowded by the memory of lawful harm',
        fear: 'being useful to certainty before evidence has earned judgment',
        desire: 'to keep weak evidence from becoming another lawful sentence',
        contradiction: 'was trained to obey decisive orders, yet now distrusts the comfort decisiveness gives frightened people',
      },
      backstory: {
        origin: 'Corvin Hale left the companies after years of paid violence and took road work that asked for strength, not judgment, until a royal writ put judgment back in his hands.',
        wound: 'Corvin once helped execute a noble on weak evidence because the order was lawful; years later, the noble was proven innocent.',
        want: 'He wants the Redvale investigation to move slowly enough that no frightened certainty becomes another sentence.',
        privateKnowledge: 'People who sound most certain are often deciding who can be safely spent.',
      },
      memory: ['Corvin held the line at an execution where every seal was proper and every witness sounded certain; months later, the noble’s innocence was proven and obedience did not become innocence with it.'],
    },
  ],
  nodes: [
    {
      id: 'graymere-yard',
      name: 'Graymere Yard',
      publicName: 'Graymere Hall',
      canonicalDescription: 'Graymere Hall is the muddy seat of King Osric, where opened graves become testimony, liability, doctrine, clerical error, or accusation depending on who speaks first.',
      description: 'The muddy seat of King Osric, where opened graves become testimony, liability, doctrine, clerical error, or accusation depending on who speaks first.',
      explorationHint: 'Mud-dark roads lead away from the hall under a low sky and too many confident answers.',
      iconAssetId: 'road',
      nodeType: 'origin',
      exits: [
        { toNodeId: 'ash-farms', direction: 'west', label: 'Follow the opened graves toward Redvale' },
        { toNodeId: 'old-watchtower', direction: 'east', label: 'Take the high road toward Father Aldric’s tower' },
      ],
      unfinishedBusiness: [
        {
          id: 'answer-royal-order',
          label: 'Answer the royal order',
          reason: 'The royal order must be answered before the roads out of Graymere Hall become an investigation rather than an escape.',
          activeEventId: 'royal-order',
          clearedByFlag: 'royal-order-answered',
        },
      ],
      nextNodeIds: ['ash-farms', 'old-watchtower'],
      mapPosition: { x: 300, y: 520 },
      eventWeights: [
        { eventId: 'royal-order', weight: 8 },
        { eventId: 'court-preparation', weight: 3 },
        { eventId: 'village-plea', weight: 2 },
      ],
    },
    {
      id: 'ash-farms',
      name: 'Ash Farms',
      publicName: 'Ash Farms',
      canonicalDescription: 'Ash Farms is a famine-scarred stretch outside Redvale where opened graves have made families compare memory against records they were once forced to accept.',
      description: 'Famine-scarred fields outside Redvale, where families compare memory against records they were once forced to accept.',
      explorationHint: 'A rutted farm road sinks into fields, opened graves, and families who remember more than they can safely prove.',
      iconAssetId: 'crossroads',
      nodeType: 'settlement',
      exits: [
        { toNodeId: 'graymere-yard', direction: 'east', label: 'Return to the king’s road' },
        { toNodeId: 'blackpine-road', direction: 'north', label: 'Follow the rumor road into the pines' },
        { toNodeId: 'old-watchtower', direction: 'northeast', label: 'Cut across the high fields toward the old tower' },
      ],
      nextNodeIds: ['graymere-yard', 'blackpine-road', 'old-watchtower'],
      mapPosition: { x: 180, y: 385 },
      eventWeights: [
        { eventId: 'maren-ledger', weight: 8 },
        { eventId: 'village-plea', weight: 3 },
        { eventId: 'fog-of-witnesses', weight: 2 },
      ],
    },
    {
      id: 'old-watchtower',
      name: 'Old Watchtower',
      publicName: 'Old Watchtower',
      canonicalDescription: 'The Old Watchtower shelters Father Aldric’s crossed-out sermons, old burial marks, and a priestly refusal to let fear harden into doctrine.',
      description: 'A leaning hill tower crowded with crossed-out sermons, old burial marks, and a priest who mistrusts every clean answer.',
      explorationHint: 'A high path climbs toward broken stone, old warning marks, and a window lit late by sermon drafts.',
      iconAssetId: 'codex',
      nodeType: 'watch',
      exits: [
        { toNodeId: 'graymere-yard', direction: 'west', label: 'Descend toward Graymere Hall' },
        { toNodeId: 'ash-farms', direction: 'southwest', label: 'Cross back toward the fields' },
        { toNodeId: 'blackpine-road', direction: 'northwest', label: 'Take the marked road under the pines' },
        { toNodeId: 'barrow-crypt', direction: 'north', label: 'Follow the tower map toward the barrow records' },
      ],
      nextNodeIds: ['graymere-yard', 'ash-farms', 'blackpine-road', 'barrow-crypt'],
      mapPosition: { x: 420, y: 385 },
      eventWeights: [
        { eventId: 'aldric-sermon', weight: 7 },
        { eventId: 'court-preparation', weight: 2 },
        { eventId: 'fog-of-witnesses', weight: 3 },
      ],
    },
    {
      id: 'blackpine-road',
      name: 'Blackpine Road',
      publicName: 'Blackpine Road',
      canonicalDescription: 'Blackpine Road is a cramped forest road where cart ruts, tool marks, frightened witnesses, and missing grave goods can be made to accuse almost anyone.',
      description: 'A cramped forest road where cart ruts, tool marks, frightened witnesses, and missing grave goods can be made to accuse almost anyone.',
      explorationHint: 'Black pines crowd a road where rumors travel faster than carts.',
      iconAssetId: 'forest',
      nodeType: 'hazard',
      exits: [
        { toNodeId: 'ash-farms', direction: 'south', label: 'Return by the farm track' },
        { toNodeId: 'old-watchtower', direction: 'southeast', label: 'Climb back toward the tower' },
        { toNodeId: 'barrow-crypt', direction: 'north', label: 'Press toward the old barrow' },
      ],
      nextNodeIds: ['ash-farms', 'old-watchtower', 'barrow-crypt'],
      mapPosition: { x: 285, y: 250 },
      eventWeights: [
        { eventId: 'fog-of-witnesses', weight: 8 },
        { eventId: 'roadside-toll', weight: 3 },
        { eventId: 'maren-ledger', weight: 1 },
      ],
    },
    {
      id: 'barrow-crypt',
      name: 'Old Barrow',
      publicName: 'Old Barrow',
      canonicalDescription: 'The Old Barrow is a cold archive of bodies, names, old tokens, and famine corrections that refuses to tell one clean story.',
      description: 'A cold archive of bodies, names, old tokens, and famine corrections that refuses to tell one clean story.',
      explorationHint: 'A grass-swallowed mound waits ahead with stone teeth showing and too many meanings inside.',
      iconAssetId: 'keep',
      nodeType: 'crypt',
      exits: [
        { toNodeId: 'old-watchtower', direction: 'south', label: 'Retreat by the tower path' },
        { toNodeId: 'blackpine-road', direction: 'southwest', label: 'Return through Blackpine Road' },
        {
          toNodeId: 'king-return',
          direction: 'east',
          label: 'Return to court with contested evidence',
          blocker: {
            id: 'contested-evidence-required',
            label: 'Contested evidence required',
            reason: 'Returning to court without contested evidence would let the first confident faction define Redvale before the graves can contradict them.',
            requiredItemId: 'contested-evidence',
          },
        },
      ],
      nextNodeIds: ['old-watchtower', 'blackpine-road', 'king-return'],
      mapPosition: { x: 300, y: 110 },
      eventWeights: [
        { eventId: 'barrow-contradictions', weight: 10 },
        { eventId: 'contested-evidence-glimpse', weight: 3 },
      ],
    },
    {
      id: 'king-return',
      name: 'King Return',
      publicName: 'Graymere Hall Return',
      canonicalDescription: 'Graymere Hall Return is the court’s reckoning point, where evidence becomes policy, doctrine, riot, correction, or official uncertainty.',
      description: 'The court’s reckoning point, where evidence becomes policy, doctrine, riot, correction, or official uncertainty.',
      explorationHint: 'Torch smoke and court noise gather beyond the road back.',
      iconAssetId: 'lantern',
      nodeType: 'court',
      exits: [{ toNodeId: 'barrow-crypt', direction: 'west', label: 'Go back toward the barrow road' }],
      nextNodeIds: ['barrow-crypt'],
      mapPosition: { x: 470, y: 65 },
      eventWeights: [{ eventId: 'royal-proof', weight: 10 }],
    },
  ],
  events: [
    {
      id: 'royal-order',
      name: 'The hall asks what truth will cost',
      weight: 4,
      iconAssetId: 'road',
      prompt: 'King Osric orders an investigation into Redvale’s opened graves while Royal Archivist Renwick guards the famine ledgers like a second throne. No one in the hall agrees what happened, but everyone understands that the surviving explanation will decide who is blamed, forgiven, erased, or believed.',
      currentHint: 'Get the royal order into plain words before choosing which road leaves the hall.',
      objectiveNodeId: 'ash-farms',
      npcTemplate: {
        id: 'king-osric',
        name: 'King Osric',
        role: 'Tired king',
        canonicalDescription: 'King Osric is a thin ruler in a patched crown who fears panic more than ghosts and hopes an answer can still behave like mercy.',
        description: 'A thin ruler in a patched crown who fears panic more than ghosts.',
        voice: 'formal, clipped, ashamed when pressed, impatient with uncertainty',
        want: 'Contain Redvale’s panic before it becomes rebellion, riot, or proof that royal order cannot protect its dead.',
        knows: 'Famine-era burials around Redvale were poorly documented, and the records frighten his court more than the opened graves do.',
      },
      choices: [
        {
          id: 'ask-if-culprit-satisfies-court',
          label: 'If I bring you a culprit before I bring you doubt, will that satisfy the court?',
          neutralSummary: 'You challenged the court’s hunger for a clean accused person before accepting the order.',
          writerIntent: 'Offer a direct question that exposes the difference between order and truth.',
          actionPrompt: 'The selected option is to ask King Osric exactly whether a culprit would satisfy the court before evidence has earned one.',
          mode: 'ask',
          displayStyle: 'dialogue',
          skillTags: ['plain-speech'],
          effects: [
            { type: 'setFlag', flag: 'royal-order-answered', value: true },
            { type: 'remember', text: 'King Osric needs the investigation to prevent panic, but his hall is already hungry for a culprit.' },
            { type: 'revealNode', nodeId: 'ash-farms' },
            { type: 'moveToNode', nodeId: 'ash-farms' },
          ],
        },
        {
          id: 'ask-for-famine-records',
          label: 'Show me the famine records before anyone tells me what they prove.',
          neutralSummary: 'You treated the records as contested evidence rather than settled authority.',
          writerIntent: 'Offer an investigative opening that brings Renwick and the archive into the central conflict.',
          actionPrompt: 'The selected option is to ask for the famine records before accepting any interpretation of the opened graves.',
          mode: 'ask',
          displayStyle: 'dialogue',
          skillTags: ['grave-lore'],
          effects: [
            { type: 'setFlag', flag: 'royal-order-answered', value: true },
            { type: 'remember', text: 'Royal Archivist Renwick warned that if records can be wrong, kingdoms cannot exist.' },
            { type: 'revealNode', nodeId: 'old-watchtower' },
            { type: 'moveToNode', nodeId: 'old-watchtower' },
          ],
        },
      ],
    },
    {
      id: 'court-preparation',
      name: 'The court prepares a conclusion',
      weight: 5,
      iconAssetId: 'lantern',
      prompt: 'A court clerk lays out road warrants, restraint cords, tools, and three draft proclamations with blank spaces where a cause and culprit can be written later.',
      currentHint: 'Take what helps the investigation without accepting the conclusion being prepared for it.',
      objectiveNodeId: 'old-watchtower',
      choices: [
        {
          id: 'refuse-chains-before-names',
          label: 'Do not give me chains before I have names.',
          neutralSummary: 'You refused equipment that assumed judgment before evidence.',
          writerIntent: 'Give the player a spoken refusal that challenges court certainty while still securing practical tools.',
          actionPrompt: 'The selected option is to tell the clerk not to hand over chains before the investigation has names, facts, and contested evidence.',
          mode: 'say',
          displayStyle: 'dialogue',
          skillTags: ['plain-speech'],
          effects: [
            { type: 'gainItem', item: betterKnife },
            { type: 'remember', text: 'The court had restraint cords and draft proclamations ready before the investigation had evidence.' },
            { type: 'setFlag', flag: 'court-certainty-questioned', value: true },
            { type: 'moveToNode', nodeId: 'old-watchtower' },
          ],
        },
        {
          id: 'take-tools-not-verdicts',
          label: 'I will take tools, not a verdict.',
          neutralSummary: 'You converted the court’s preparation into practical equipment without accepting its framing.',
          writerIntent: 'Offer a practical option that still reinforces the central conflict over imposed interpretation.',
          actionPrompt: 'The selected option is to take useful tools and reject the court’s prepared conclusions.',
          mode: 'say',
          displayStyle: 'dialogue',
          skillTags: ['steady-hands'],
          effects: [
            { type: 'gainItem', item: crackedSpearHead },
            { type: 'remember', text: 'Court preparation can preserve order, but it can also make judgment feel inevitable.' },
            { type: 'moveToNode', nodeId: 'old-watchtower' },
          ],
        },
      ],
    },
    {
      id: 'village-plea',
      name: 'A farmer asks which truth will bury him',
      weight: 3,
      iconAssetId: 'crossroads',
      prompt: 'Farmer Riel blocks the road with a child behind him and asks whether the royal writ has come to correct Redvale or make one more official lie durable.',
      currentHint: 'Listen for what the farms know and what they need the court to stop forgetting.',
      objectiveNodeId: 'ash-farms',
      npcTemplate: {
        id: 'farmer-riel',
        name: 'Farmer Riel',
        role: 'Frightened father',
        canonicalDescription: 'Farmer Riel is a raw-eyed farmer with mud on his knees, a child gripping his coat, and a memory of famine relief that came only after his family accepted the wrong name.',
        description: 'A raw-eyed farmer with mud on his knees and a child gripping the back of his coat.',
        voice: 'plain, guarded, angry from fear, defensive when records are praised',
        want: 'Make the court hear that Redvale’s families accepted wrong bodies because survival left them little room to argue.',
        knows: 'The first disputed grave was not the first opened grave; it was the first one villagers dared contradict aloud.',
      },
      choices: [
        {
          id: 'promise-no-record-worship',
          label: 'I will not promise the record is true just because it is written.',
          neutralSummary: 'You gave a limited honest answer that respected village memory without declaring every record false.',
          writerIntent: 'Offer an empathetic spoken answer that stays honest about uncertainty and centers villager memory.',
          actionPrompt: 'The selected option is to tell Farmer Riel exactly that the record is not true merely because it is written.',
          mode: 'say',
          displayStyle: 'dialogue',
          skillTags: ['plain-speech'],
          effects: [
            { type: 'remember', text: 'Redvale families accepted famine bodies under official names because refusing the record meant losing relief, burial, or inheritance.' },
            { type: 'setFlag', flag: 'villager-memory-heard', value: true },
            { type: 'moveToNode', nodeId: 'ash-farms' },
          ],
        },
        {
          id: 'ask-first-disagreement',
          label: 'Show me the grave where memory and record first disagreed.',
          neutralSummary: 'You focused the exchange on the first contradiction rather than the loudest rumor.',
          writerIntent: 'Offer an investigative question that makes a clue reveal family pressure and record failure.',
          actionPrompt: 'The selected option is to ask Farmer Riel for the grave where living memory first contradicted the written record.',
          mode: 'ask',
          displayStyle: 'dialogue',
          skillTags: ['grave-lore'],
          effects: [
            { type: 'remember', text: 'The first disputed grave was opened quietly; the family hid it because the record protected their famine compensation and their shame.' },
            { type: 'moveToNode', nodeId: 'ash-farms' },
          ],
        },
      ],
    },
    {
      id: 'maren-ledger',
      name: 'Maren remembers graves, not faces',
      weight: 5,
      iconAssetId: 'codex',
      prompt: 'Maren kneels beside three opened famine graves and recites names, families, and burial years with perfect care, then looks through a grieving son as if his face has never happened twice.',
      currentHint: 'Use Maren’s memory without pretending it settles every contradiction.',
      objectiveNodeId: 'blackpine-road',
      npcTemplate: {
        id: 'maren',
        name: 'Maren',
        role: 'Burial rememberer',
        canonicalDescription: 'Maren can recite every grave, name, family, and burial year in Redvale, then look at a living face as if it has never happened twice.',
        description: 'A burial rememberer who knows every grave and forgets every face.',
        voice: 'precise, apologetic, unnerving, intimate about the dead and lost among the living',
        want: 'Make the graves match the names she remembers, even if that ruins what the village survived by believing.',
        knows: 'Several famine burials were recorded under names that do not fit the bodies, but Maren cannot always tell which living relatives lied, guessed, or needed the record to hold.',
      },
      choices: [
        {
          id: 'ask-maren-for-graves-not-faces',
          label: 'Tell me the graves as you remember them, not the people standing here.',
          neutralSummary: 'You used Maren’s strange strength while respecting its limits.',
          writerIntent: 'Offer a direct question that makes Maren useful and unsettling without making her omniscient.',
          actionPrompt: 'The selected option is to ask Maren to recite the graves as she remembers them, not the faces around them.',
          mode: 'ask',
          displayStyle: 'dialogue',
          skillTags: ['grave-lore'],
          effects: [
            { type: 'remember', text: 'Maren recited three famine graves whose names, families, and recorded burial order cannot all be true; she remembered each grave perfectly and failed to recognize one living son beside it.' },
            { type: 'setFlag', flag: 'maren-contradictions-recorded', value: true },
            { type: 'moveToNode', nodeId: 'blackpine-road' },
          ],
        },
        {
          id: 'check-body-not-name',
          label: 'Check the hands, the height, the old breaks — not only the name.',
          neutralSummary: 'You tested the body against memory and record instead of allowing the written name to end the question.',
          writerIntent: 'Offer a Tamsin-facing investigation choice that reopens her personal wound through external evidence.',
          actionPrompt: 'The selected option is to check physical identifiers against the written name, making the discovery concrete and visible.',
          mode: 'act',
          displayStyle: 'action',
          skillTags: ['grave-lore', 'mental-fortitude'],
          effects: [
            { type: 'remember', text: 'One opened famine grave held a body recorded under a name the family had accepted because refusing it would have cost them relief.' },
            { type: 'remember', text: 'The discovery echoed Tamsin’s brother: a body delivered under a correct name that did not make it true.' },
            { type: 'setFlag', flag: 'tamsin-wound-reopened', value: true },
            { type: 'moveToNode', nodeId: 'blackpine-road' },
          ],
        },
        {
          id: 'separate-fact-from-accusation',
          label: 'Mark what we know separately from what we want it to prove.',
          neutralSummary: 'You separated evidence from accusation before grief could choose a target.',
          writerIntent: 'Offer a Corvin-facing discipline choice shaped by his fear of weak evidence becoming punishment.',
          actionPrompt: 'The selected option is to separate known facts from accusations at the opened graves.',
          mode: 'act',
          displayStyle: 'action',
          skillTags: ['steady-hands', 'plain-speech'],
          effects: [
            { type: 'remember', text: 'Corvin separated fact from accusation: wrong record, opened grave, frightened witness, unknown hand.' },
            { type: 'setFlag', flag: 'corvin-evidence-discipline', value: true },
            { type: 'moveToNode', nodeId: 'blackpine-road' },
          ],
        },
      ],
    },
    {
      id: 'aldric-sermon',
      name: 'Father Aldric crosses out certainty',
      weight: 5,
      iconAssetId: 'codex',
      prompt: 'Father Aldric’s tower room is papered with sermons crossed out at the moment they became too satisfying. Outside, villagers wait for the Church to name a cause he refuses to make clean.',
      currentHint: 'Learn what the Church can see clearly and what it risks turning into doctrine.',
      objectiveNodeId: 'barrow-crypt',
      npcTemplate: {
        id: 'father-aldric',
        name: 'Father Aldric',
        role: 'Redvale priest',
        canonicalDescription: 'Father Aldric is a sleepless village priest with ink-stained fingers, a stack of crossed-out sermons, and no patience for holy certainty.',
        description: 'A sleepless village priest with ink-stained fingers and a stack of crossed-out sermons.',
        voice: 'careful, self-correcting, humane, maddeningly unwilling to give one clean answer',
        want: 'Keep the village from turning fear into a doctrine that lets them punish someone convenient.',
        knows: 'He has not repeated a sermon in years because he believes certainty is the root of cruelty; the opened graves began after famine burials whose rites were shortened, confused, or recorded too cleanly.',
      },
      choices: [
        {
          id: 'ask-why-sermons-change',
          label: 'Why have you not preached the same answer twice?',
          neutralSummary: 'You pressed Aldric on why he refuses the fixed explanation his village wants.',
          writerIntent: 'Offer a direct question that reveals Aldric’s theology of uncertainty and its social cost.',
          actionPrompt: 'The selected option is to ask Father Aldric why he has not preached the same answer twice.',
          mode: 'ask',
          displayStyle: 'dialogue',
          skillTags: ['plain-speech'],
          effects: [
            { type: 'remember', text: 'Father Aldric rewrites every sermon because he believes certainty is the root of cruelty.' },
            { type: 'remember', text: 'The villagers resent Aldric because his mercy gives them no clean target.' },
            { type: 'moveToNode', nodeId: 'barrow-crypt' },
          ],
        },
        {
          id: 'ask-famine-rites',
          label: 'Which rites were changed during the famine?',
          neutralSummary: 'You asked for ritual changes as evidence of social fracture, not automatic supernatural cause.',
          writerIntent: 'Offer an investigative question that reveals Church insight while keeping multiple interpretations open.',
          actionPrompt: 'The selected option is to ask Father Aldric which burial rites changed during the famine and why those changes still matter.',
          mode: 'ask',
          displayStyle: 'dialogue',
          skillTags: ['grave-lore'],
          effects: [
            { type: 'gainItem', item: bellClapper },
            { type: 'remember', text: 'Famine burials were shortened, doubled, and sometimes named after the record rather than the body.' },
            { type: 'remember', text: 'The missing bell clapper may be sacrilege, theft, panic, sabotage, or only an old absence newly noticed.' },
            { type: 'revealNode', nodeId: 'barrow-crypt' },
            { type: 'moveToNode', nodeId: 'barrow-crypt' },
          ],
        },
      ],
    },
    {
      id: 'fog-of-witnesses',
      name: 'The road changes with each telling',
      weight: 6,
      iconAssetId: 'forest',
      prompt: 'On Blackpine Road, fog, cart ruts, cut roots, and frightened witnesses rearrange with every account. None of them sound simple enough to dismiss.',
      currentHint: 'Preserve contradictions without letting fog become a verdict.',
      objectiveNodeId: 'barrow-crypt',
      choices: [
        {
          id: 'mark-ground-before-fear',
          label: 'Mark what the ground says before asking what fear saw.',
          neutralSummary: 'You prioritized physical traces without declaring witness fear useless.',
          writerIntent: 'Offer a practical investigation choice that keeps physical evidence and witness testimony in tension.',
          actionPrompt: 'The selected option is to mark cart ruts, footprints, disturbed soil, and tool cuts before interpreting frightened testimony.',
          mode: 'act',
          displayStyle: 'action',
          skillTags: ['grave-lore', 'steady-hands'],
          effects: [
            { type: 'remember', text: 'The road held cart ruts, hurried footprints, and disturbed soil, but no trace explained why graves opened across different parts of Redvale.' },
            { type: 'moveToNode', nodeId: 'barrow-crypt' },
          ],
        },
        {
          id: 'let-witnesses-contradict',
          label: 'Let the witnesses contradict each other without calling one a liar.',
          neutralSummary: 'You treated contradiction as evidence of pressure rather than proof of falsehood.',
          writerIntent: 'Offer a wait/listen choice that supports collective panic as plausible without dismissing the strange events.',
          actionPrompt: 'The selected option is to let witnesses contradict each other and preserve the contradictions as part of the evidence.',
          mode: 'wait',
          displayStyle: 'passive',
          skillTags: ['mental-fortitude', 'plain-speech'],
          effects: [
            { type: 'remember', text: 'Witnesses disagreed about bells, lights, figures, and timing; the contradictions looked like panic, trauma, concealment, or all three.' },
            { type: 'setFlag', flag: 'collective-panic-plausible', value: true },
            { type: 'moveToNode', nodeId: 'barrow-crypt' },
          ],
        },
        {
          id: 'no-judgment-from-fog',
          label: 'No judgment from fog.',
          neutralSummary: 'You refused to let unclear testimony become grounds for punishment.',
          writerIntent: 'Offer a Corvin-facing spoken principle born from his execution wound.',
          actionPrompt: 'The selected option is to say exactly that no judgment should be made from fog and frightened testimony alone.',
          mode: 'say',
          displayStyle: 'dialogue',
          skillTags: ['plain-speech'],
          effects: [
            { type: 'remember', text: 'Corvin refused to let frightened testimony become a sentence, remembering the innocent noble condemned by confident men.' },
            { type: 'setFlag', flag: 'corvin-resists-certainty', value: true },
            { type: 'moveToNode', nodeId: 'barrow-crypt' },
          ],
        },
      ],
    },
    {
      id: 'roadside-toll',
      name: 'The hungry sell explanations',
      weight: 2,
      iconAssetId: 'crossroads',
      prompt: 'Sergeant Maud and her hungry deserters stop travelers under the pines. They sell passage, rumors, and whatever explanation will buy bread by nightfall.',
      currentHint: 'Get past the deserters while learning who profits from Redvale sounding cursed.',
      objectiveNodeId: 'barrow-crypt',
      npcTemplate: {
        id: 'sergeant-maud',
        name: 'Sergeant Maud',
        role: 'Deserter with a borrowed sword',
        canonicalDescription: 'Sergeant Maud is a hollow-cheeked veteran whose shame has hardened into toll-taking and rumor brokerage.',
        description: 'A hollow-cheeked veteran whose shame has hardened into toll-taking.',
        voice: 'dry, threatening, tired beneath the threat, practical about fear as currency',
        want: 'Keep her deserters alive another week by selling passage and repeating whichever story buys food.',
        knows: 'Paid rumors naming curse, fraud, and royal weakness reached Blackpine Road before any investigator did.',
      },
      choices: [
        {
          id: 'ask-who-benefits-cursed-redvale',
          label: 'Who benefits when Redvale sounds cursed?',
          neutralSummary: 'You treated rumor as evidence of incentives rather than proof of cause.',
          writerIntent: 'Offer a direct question that makes political sabotage plausible without settling it.',
          actionPrompt: 'The selected option is to ask Sergeant Maud who benefits when Redvale sounds cursed.',
          mode: 'ask',
          displayStyle: 'dialogue',
          skillTags: ['plain-speech'],
          effects: [
            { type: 'remember', text: 'Paid rumors named necromancy before investigators reached the graves, making political sabotage plausible without proving it.' },
            { type: 'setFlag', flag: 'sabotage-plausible', value: true },
            { type: 'moveToNode', nodeId: 'barrow-crypt' },
          ],
        },
        {
          id: 'trade-knife-for-rumor-names',
          label: 'Trade the Armory Knife for the names you were told to repeat.',
          neutralSummary: 'You gave up a useful object to expose how rumor moved ahead of evidence.',
          writerIntent: 'Offer a careful inventory trade that links survival, rumor, and competing explanations.',
          actionPrompt: 'The selected option is to trade the Armory Knife for the names and explanations Maud was paid to repeat.',
          mode: 'use-item',
          displayStyle: 'action',
          skillTags: ['plain-speech'],
          requiresItem: 'armory-knife',
          effects: [
            { type: 'loseItem', itemId: 'armory-knife' },
            { type: 'remember', text: 'The deserters repeated three different explanations depending on who fed them: curse, fraud, and royal weakness.' },
            { type: 'moveToNode', nodeId: 'barrow-crypt' },
          ],
        },
        {
          id: 'refuse-overread-theft',
          label: 'Grave theft is a crime, not yet a cause.',
          neutralSummary: 'You acknowledged exploitation without letting it explain everything.',
          writerIntent: 'Offer a disciplined evidence choice that keeps grave robbers plausible but unproven as the cause.',
          actionPrompt: 'The selected option is to state that grave theft is a crime but not yet the cause of all opened graves.',
          mode: 'say',
          displayStyle: 'dialogue',
          skillTags: ['plain-speech', 'steady-hands'],
          effects: [
            { type: 'remember', text: 'Missing grave goods prove someone exploited opened graves, but not that thieves opened them first.' },
            { type: 'setFlag', flag: 'grave-robbers-plausible', value: true },
            { type: 'moveToNode', nodeId: 'barrow-crypt' },
          ],
        },
      ],
    },
    {
      id: 'contested-evidence-glimpse',
      name: 'The evidence refuses one meaning',
      weight: 4,
      iconAssetId: 'keep',
      prompt: 'In the Old Barrow, copied famine entries, grave soil, old tokens, and disturbed niches sit close enough to look like one answer. They are not one answer unless someone makes them one.',
      currentHint: 'Collect evidence in a way that keeps its contradictions visible.',
      objectiveNodeId: 'king-return',
      choices: [
        {
          id: 'wrap-evidence-separately',
          label: 'Wrap soil, token, and copied entries separately.',
          neutralSummary: 'You preserved different kinds of evidence without forcing them into one conclusion.',
          writerIntent: 'Offer a careful evidence-collection option that grants the required item while preserving ambiguity.',
          actionPrompt: 'The selected option is to wrap soil, token, witness marks, and copied entries separately for court.',
          mode: 'act',
          displayStyle: 'action',
          skillTags: ['steady-hands', 'grave-lore'],
          effects: [
            { type: 'gainItem', item: contestedEvidence },
            { type: 'remember', text: 'The evidence bundle contains grave soil, copied famine entries, a disputed token, and witness marks; none explains the openings alone.' },
            { type: 'setFlag', flag: 'contested-evidence-collected', value: true },
            { type: 'moveToNode', nodeId: 'king-return' },
          ],
        },
        {
          id: 'share-chain-of-custody',
          label: 'Make every witness mark the bundle before court touches it.',
          neutralSummary: 'You made the evidence harder for any one faction to claim cleanly.',
          writerIntent: 'Offer a procedural social option that gives villagers, church, and court a visible stake in the same evidence.',
          actionPrompt: 'The selected option is to have witnesses from different factions mark the evidence bundle before court controls it.',
          mode: 'act',
          displayStyle: 'action',
          skillTags: ['plain-speech', 'steady-hands'],
          effects: [
            { type: 'gainItem', item: contestedEvidence },
            { type: 'remember', text: 'Villagers, church, and royal officers marked the evidence bundle, making it harder for any one faction to claim it cleanly.' },
            { type: 'setFlag', flag: 'chain-of-custody-shared', value: true },
            { type: 'moveToNode', nodeId: 'king-return' },
          ],
        },
      ],
    },
    {
      id: 'barrow-contradictions',
      name: 'The barrow keeps too many answers',
      weight: 10,
      iconAssetId: 'keep',
      prompt: 'Inside the Old Barrow, copied famine entries, opened niches, missing grave goods, old ritual objects, and disturbed bodies sit close enough to look like one answer. They are not one answer unless someone makes them one.',
      currentHint: 'Leave the barrow with evidence that can survive court without becoming a convenient lie.',
      objectiveNodeId: 'king-return',
      choices: [
        {
          id: 'list-six-answers',
          label: 'List every explanation the evidence can bear.',
          neutralSummary: 'You preserved all plausible interpretations rather than choosing the most useful one.',
          writerIntent: 'Offer the core investigation choice: maintain six plausible explanations without proving one.',
          actionPrompt: 'The selected option is to list every explanation the barrow evidence can bear and preserve them for court.',
          mode: 'act',
          displayStyle: 'action',
          skillTags: ['grave-lore', 'mental-fortitude'],
          effects: [
            { type: 'gainItem', item: contestedEvidence },
            { type: 'remember', text: 'The barrow evidence can support necromancy, grave robbers, famine record fraud, political sabotage, collective panic, and unknown cause without proving any one of them.' },
            { type: 'setFlag', flag: 'six-theories-preserved', value: true },
            { type: 'moveToNode', nodeId: 'king-return' },
          ],
        },
        {
          id: 'find-force-corrected-names',
          label: 'Find the names that were made correct by force.',
          neutralSummary: 'You focused on famine corrections that made wrong bodies officially usable.',
          writerIntent: 'Offer a Tamsin-facing climax choice that makes record violence personal without solving the whole mystery.',
          actionPrompt: 'The selected option is to find famine corrections that made names correct after bodies were already buried.',
          mode: 'act',
          displayStyle: 'action',
          skillTags: ['grave-lore', 'mental-fortitude'],
          effects: [
            { type: 'gainItem', item: contestedEvidence },
            { type: 'remember', text: 'The barrow records showed famine corrections made after bodies were already buried, reopening Tamsin’s memory of her brother’s wrong body.' },
            { type: 'setFlag', flag: 'tamsin-wound-reopened', value: true },
            { type: 'moveToNode', nodeId: 'king-return' },
          ],
        },
        {
          id: 'hold-judgment-back',
          label: 'Separate evidence from accusation before fear can choose.',
          neutralSummary: 'You kept weak evidence from becoming a public sentence.',
          writerIntent: 'Offer a Corvin-facing climax choice that centers evidence discipline.',
          actionPrompt: 'The selected option is to separate evidence from accusation in the barrow before fear can choose a culprit.',
          mode: 'act',
          displayStyle: 'action',
          skillTags: ['steady-hands', 'plain-speech'],
          effects: [
            { type: 'gainItem', item: contestedEvidence },
            { type: 'remember', text: 'Corvin held back judgment where once he had obeyed it, keeping weak evidence from becoming another execution.' },
            { type: 'setFlag', flag: 'corvin-resists-certainty', value: true },
            { type: 'moveToNode', nodeId: 'king-return' },
          ],
        },
      ],
    },
    {
      id: 'royal-proof',
      name: 'The court decides which truth survives',
      weight: 10,
      iconAssetId: 'lantern',
      prompt: 'King Osric convenes court over Redvale’s opened graves. Father Aldric will not name a curse, the villagers will not trust the ledgers, Royal Archivist Renwick will not let the ledgers fail, and the court wants an answer before fear becomes policy without them.',
      currentHint: 'Decide how the evidence enters public truth without letting one faction own it completely.',
      npcTemplate: {
        id: 'royal-archivist-renwick',
        name: 'Royal Archivist Renwick',
        role: 'Keeper of royal records',
        canonicalDescription: 'Royal Archivist Renwick is a spare, orderly man who treats a corrected record like a cracked foundation stone.',
        description: 'A spare, orderly archivist with clean cuffs and frightened eyes.',
        voice: 'measured, sincere, precise, quietly terrified of disorder',
        want: 'Protect the authority of records because famine relief, inheritance, taxes, pardons, and royal legitimacy all depend on them being trusted.',
        knows: 'Some famine ledgers contain impossible consistencies; if records can be wrong, kingdoms cannot exist.',
      },
      choices: [
        {
          id: 'preserve-contested-truth',
          label: 'Record what we know, what we fear, and what we cannot yet prove.',
          neutralSummary: 'You forced the court to preserve uncertainty as public record rather than private weakness.',
          writerIntent: 'Offer an ending where uncertainty survives officially without becoming paralysis.',
          actionPrompt: 'The selected option is to tell the court exactly to record what is known, feared, and not yet proven.',
          mode: 'say',
          displayStyle: 'dialogue',
          skillTags: ['plain-speech', 'mental-fortitude'],
          requiresItem: 'contested-evidence',
          effects: [
            { type: 'remember', text: 'The court was forced to preserve uncertainty as part of the official record instead of disguising it as weakness.' },
            { type: 'setFlag', flag: 'uncertainty-preserved', value: true },
            { type: 'setFlag', flag: 'interpretation-delivered', value: true },
          ],
        },
        {
          id: 'correct-the-famine-records',
          label: 'A kingdom that cannot correct a record is already lying.',
          neutralSummary: 'You challenged Renwick without destroying the idea that records matter.',
          writerIntent: 'Offer an ending where correction becomes the price of record authority.',
          actionPrompt: 'The selected option is to tell Renwick and the court exactly that a kingdom unable to correct records is already lying.',
          mode: 'say',
          displayStyle: 'dialogue',
          skillTags: ['grave-lore', 'plain-speech'],
          requiresItem: 'contested-evidence',
          effects: [
            { type: 'remember', text: 'Renwick heard the records challenged without being burned: correction became the price of keeping them useful.' },
            { type: 'setFlag', flag: 'famine-records-challenged', value: true },
            { type: 'setFlag', flag: 'interpretation-delivered', value: true },
          ],
        },
        {
          id: 'refuse-easy-culprit',
          label: 'No one dies today for evidence that still has six meanings.',
          neutralSummary: 'You prevented the court from turning ambiguous evidence into a sentence.',
          writerIntent: 'Offer a Corvin-facing ending that resists lawful harm through evidence discipline.',
          actionPrompt: 'The selected option is to tell the court exactly that no one dies for evidence that still has six meanings.',
          mode: 'say',
          displayStyle: 'dialogue',
          skillTags: ['plain-speech', 'steady-hands'],
          requiresItem: 'contested-evidence',
          effects: [
            { type: 'remember', text: 'Corvin refused to let weak evidence become another lawful killing.' },
            { type: 'setFlag', flag: 'easy-culprit-refused', value: true },
            { type: 'setFlag', flag: 'interpretation-delivered', value: true },
          ],
        },
        {
          id: 'name-wrong-bodies',
          label: 'Read the wrong bodies into the record before you ask who opened the graves.',
          neutralSummary: 'You centered the famine wound before the court could reduce the case to cause and culprit.',
          writerIntent: 'Offer a Tamsin-facing ending that makes official correction and remembered harm inseparable.',
          actionPrompt: 'The selected option is to demand that the court read wrong bodies into the record before arguing over cause.',
          mode: 'say',
          displayStyle: 'dialogue',
          skillTags: ['grave-lore', 'plain-speech'],
          requiresItem: 'contested-evidence',
          effects: [
            { type: 'remember', text: 'Tamsin made the court hear that a recorded name can be correct and still bury a lie.' },
            { type: 'setFlag', flag: 'wrong-bodies-named', value: true },
            { type: 'setFlag', flag: 'interpretation-delivered', value: true },
          ],
        },
      ],
    },
  ],
}

const openGravesBible: StoryBible = {
  themes: [
    'records against memory when both are necessary and both can wound',
    'good-faith institutions becoming dangerous when they cannot tolerate uncertainty',
    'grief searching for a cause that will not abandon the dead',
    'certainty as comfort, weapon, and public policy',
  ],
  tone: [
    'grounded medieval hardship',
    'plain speech under legal, spiritual, and village pressure',
    'practical grief and institutional fear',
    'ambiguity that remains concrete rather than coy',
  ],
  worldRules: storySchema.fixedRules,
  narrativeLaws: [
    'The Story Bible outranks generated prose, scene plans, and transient atmosphere.',
    'The LLM may reveal information, pressure, opportunity, dialogue, and mood, but may not create durable state.',
    'Every scene must contain information, uncertainty, and more than one meaningful approach.',
    'Future mysteries must not be resolved before listed consequences or discovered clues justify them.',
    ...WRITER_GUIDELINES,
  ],
  factions: [
    {
      id: 'graymere-court',
      name: 'Graymere Court',
      publicFace: 'Royal order, investigation, famine relief authority, and the promise that someone will be held responsible.',
      privatePressure:
        'Correct that panic could destabilize the kingdom; wrong that suppressing uncertainty will restore trust; acting in good faith to prevent collapse; dangerous because it will convert ambiguity into a sentence. Its secret fear is not the dead, but famine-era records that were poorly documented.',
      reputation: 0,
    },
    {
      id: 'redvale-church',
      name: 'Redvale Church',
      publicFace: 'Burial rites, mercy, sermons, confession, and protection from cruelty disguised as certainty.',
      privatePressure:
        'Correct that the village is spiritually fractured; wrong that the graves must have a supernatural cause; acting in good faith to keep mourners from revenge; dangerous because it may turn evidence into parable and leave material harms untouched. It fears losing authority over suffering.',
      reputation: 0,
    },
    {
      id: 'redvale-villagers',
      name: 'Redvale Villagers',
      publicFace: 'Families, farmers, grave-tenders, and famine survivors demanding that lived memory outrank distant seals.',
      privatePressure:
        'Correct that something genuinely strange is happening and the records hide wrong bodies; wrong that all strange events share the same cause; acting in good faith to defend their dead; dangerous because grief can become mob certainty. They fear being forgotten again.',
      reputation: 0,
    },
    {
      id: 'royal-archivists',
      name: 'Royal Archivists',
      publicFace: 'Ledgers, burial rolls, inheritance proofs, famine accounts, and the fragile continuity of law.',
      privatePressure:
        'Correct that records matter and let strangers cooperate across time; wrong that records matter more than memory; acting in good faith to keep the kingdom intelligible; dangerous because they will preserve falsehood rather than admit the archive can wound. They fear historical uncertainty.',
      reputation: 0,
    },
  ],
  locations: storySchema.nodes.map((node) => ({
    id: node.id,
    name: node.publicName,
    summary: node.canonicalDescription ?? node.description,
    rules: node.exits.map((exit) => `Connected to ${exit.toNodeId}${exit.blocker ? ` unless blocked: ${exit.blocker.reason}` : ''}`),
  })),
  characters: [
    ...storySchema.players.map((player) => ({
      id: player.id,
      name: `${player.firstName} ${player.lastName}`,
      role: player.role,
      wants: [player.backstory.want],
      fears: [player.voice.fear],
      knows: [player.backstory.privateKnowledge],
    })),
    ...storySchema.events
      .map((event) => event.npcTemplate)
      .filter((npc): npc is NonNullable<(typeof storySchema.events)[number]['npcTemplate']> => Boolean(npc))
      .map((npc) => ({
        id: npc.id,
        name: npc.name,
        role: npc.role,
        wants: [npc.want],
        knows: [npc.knows],
      })),
  ],
  threats: [
    {
      id: 'imposed-certainty',
      name: 'Imposed certainty',
      pressure: 'A frightened institution may choose the explanation that lets it act quickly rather than truthfully.',
      signs: ['draft proclamations', 'calls for a culprit', 'questions treated as disloyalty'],
    },
    {
      id: 'record-collapse',
      name: 'Record collapse',
      pressure: 'If every record is treated as suspect, inheritance, relief, burial, and pardon all begin to shake.',
      signs: ['impossible consistencies', 'Renwick defending ledgers like walls', 'families afraid correction will cost survival'],
    },
    {
      id: 'grief-becoming-violence',
      name: 'Grief becoming violence',
      pressure: 'Forgotten people may seize the first explanation that gives their dead an enemy.',
      signs: ['watched neighbors', 'rumors traveling before evidence', 'families hiding contradictions until fear makes them useful'],
    },
  ],
  mysteries: [
    {
      id: 'opened-graves-interpretations',
      question: 'Why does everyone need a different explanation for the opened graves?',
      knownClues: [
        'The same opened grave can be read as sacrilege, evidence tampering, panic, fraud, sabotage, or something no one understands.',
        'Every faction names the cause in a way that protects what it cannot afford to lose.',
      ],
    },
    {
      id: 'six-plausible-theories',
      question: 'Which explanation will survive: necromancy, grave robbers, famine record fraud, political sabotage, collective panic, or unknown cause?',
      knownClues: [
        'Disturbed graves and disputed tokens can suggest necromancy without confirming it.',
        'Tool marks and absent valuables can suggest grave robbers without showing theft caused the openings.',
        'Mismatched famine entries can suggest record fraud without showing who altered them.',
        'Convenient timing and paid rumors can suggest political sabotage without identifying a saboteur.',
        'Contradictory witnesses can suggest collective panic without making witnesses liars.',
        'Some evidence remains unexplained without becoming permission to invent certainty.',
      ],
    },
    {
      id: 'tamsins-wrong-body',
      question: 'What happens when the record needs to be correct more than the witness needs to be believed?',
      knownClues: [
        'Tamsin’s brother was recorded under a body she knew was not his.',
        'Redvale’s opened graves reveal other famine burials where name, body, and record do not fully agree.',
      ],
    },
  ],
  narrativePatterns: [
    { id: 'contested_evidence', purpose: 'complicate interpretation', instruction: 'Make the same concrete clue support at least two plausible explanations and reveal who benefits from each reading.' },
    { id: 'biased_testimony', purpose: 'reveal character', instruction: 'Let witnesses defend what they need to be true instead of merely dispensing information.' },
    { id: 'good_faith_danger', purpose: 'increase moral pressure', instruction: 'Show each faction acting sincerely before showing how sincerity can harm others.' },
    { id: 'clue_as_character', purpose: 'reveal information', instruction: 'Every clue should reveal the mystery and a person, institution, wound, or worldview.' },
    { id: 'public_interpretation', purpose: 'resolve without certainty', instruction: 'Final scenes decide what can be recorded, corrected, doubted, or refused, not what absolutely happened.' },
  ],
}

export const openGravesStory = {
  schema: storySchema,
  iconAssets: storyIconAssets,
  skillTagDefinitions,
  allKnownItems: [fieldSpade, blessedWater, ironNails, royalWrit, graveLedger, mirehillWhistle, betterKnife, crackedSpearHead, bellClapper, contestedEvidence],
  codexTermTargets,
  codexTermSummaries,
  runtime: {
    initialNodeId: 'graymere-yard',
    initialExploredNodeIds: ['graymere-yard'],
    victory: {
      goalNodeId: storySchema.goalNodeId,
      requiredFlag: 'interpretation-delivered',
    },
    currentObjectiveText: {
      won: 'The court has heard the opened graves as contested truth, not a convenient certainty.',
      lost: 'One faction’s certainty hardens around Redvale, and the opened graves become whatever the powerful need them to mean.',
    },
    outcomeFeedText: {
      won: 'The court record now contains contradiction, correction, and doubt. No one owns the graves alone.',
      lost: 'Redvale receives an answer clean enough to punish with and too narrow to heal anything.',
    },
    narrationStyleRule: `For texture, favor grounded medieval hardship, plain names, practical social friction, burial customs, institutional fear, and contested testimony. Do not confirm a definitive supernatural cause. The central question is why each faction needs a different explanation for the opened graves. ${WRITER_GUIDELINES.join(' ')}`,
  },
  vNext: {
    bible: openGravesBible,
  },
} satisfies StoryBundle
